jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@v3

      - name: Setup test backend server ğŸ’»
        run: yarn test:e2e:api

      - name: Create env file ğŸªª
        run: |
          echo "${{ secrets.ENV_FILE }}" > ../server/.env
          cd ../server
          pwd
          ls -al
          cat .env

      - name: Setup test database ğŸ“€
        run: yarn test:e2e:prisma

      - name: Seed test databse ğŸ’¿
        run: yarn test:e2e:prisma:seed

      - name: Cypress run ğŸ§ª
        uses: cypress-io/github-action@v5
        with:
          start: yarn dev
          wait-on: "http://localhost:5173"
          config: "baseUrl=http://localhost:5173"
          working-directory: ./client
